# Generated by Django 6.0.4 on 2026-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Наименование груза')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('origin', models.CharField(max_length=200, verbose_name='Пункт отправления')),
                ('status', models.CharField(choices=[('ordered', 'Заказано'), ('in_transit', 'В пути'), ('delivered', 'Доставлено')], default='ordered', max_length=50)),
                ('expected_arrival', models.DateField(verbose_name='Ожидаемая дата прибытия')),
            ],
        ),
    ]
