# Generated by Django 6.0.4 on 2026-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('engineer', 'Инженер'), ('builder', 'Строитель'), ('manager', 'Менеджер')], max_length=50, verbose_name='Должность')),
                ('is_local', models.BooleanField(default=True, verbose_name='Местный специалист')),
                ('shift_start', models.DateField(verbose_name='Начало вахты/смены')),
            ],
        ),
    ]
